/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from ERROR: getGeneratedExterns called without rootDir:
/** @const */
var ajf$src$material$report$2dbuilder$forms$2danalyzer$2ddialog = {};
/** @type {?} */
var monaco;
