/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from ERROR: getGeneratedExterns called without rootDir:
/** @const */
var ajf$src$material$monaco$2deditor$autocomplete$2dsingleton$2dmodel = {};
/** @type {?} */
var monaco;
// externs from ERROR: getGeneratedExterns called without rootDir:
/** @const */
var ajf$src$material$monaco$2deditor$monaco$2deditor = {};
/** @type {?} */
var monaco;
