import * as i0 from "@angular/core";
import * as i1 from "./chart-widget";
import * as i2 from "./widget";
import * as i3 from "./filter-widget";
import * as i4 from "./formula-widget";
import * as i5 from "./image-container-widget";
import * as i6 from "./image-widget";
import * as i7 from "./graph-widget";
import * as i8 from "./map-widget";
import * as i9 from "./page-break-widget";
import * as i10 from "./report";
import * as i11 from "./table-widget";
import * as i12 from "./text-widget";
import * as i13 from "@ajf/core/chart";
import * as i14 from "@ajf/core/common";
import * as i15 from "@ajf/material/image";
import * as i16 from "@ajf/core/graph";
import * as i17 from "@ajf/core/map";
import * as i18 from "@ajf/core/page-break";
import * as i19 from "@ajf/core/table";
import * as i20 from "@ajf/core/text";
import * as i21 from "@ajf/material/forms";
import * as i22 from "@angular/common";
import * as i23 from "@ajf/core/reports";
import * as i24 from "@ajf/core/transloco";
export declare class AjfReportsModule {
    static ɵfac: i0.ɵɵFactoryDeclaration<AjfReportsModule, never>;
    static ɵmod: i0.ɵɵNgModuleDeclaration<AjfReportsModule, [typeof i1.AjfChartWidgetComponent, typeof i2.AjfColumnWidgetComponent, typeof i3.AjfFilterWidgetComponent, typeof i4.AjfFormulaWidgetComponent, typeof i5.AjfImageContainerWidgetComponent, typeof i6.AjfImageWidgetComponent, typeof i7.AjfGraphWidgetComponent, typeof i2.AjfLayoutWidgetComponent, typeof i8.AjfMapWidgetComponent, typeof i9.AjfPageBreakWidgetComponent, typeof i10.AjfReportRenderer, typeof i2.AjfReportWidget, typeof i11.AjfTableWidgetComponent, typeof i12.AjfTextWidgetComponent], [typeof i13.AjfChartModule, typeof i14.AjfCommonModule, typeof i15.AjfImageModule, typeof i16.AjfGraphModule, typeof i17.AjfMapModule, typeof i18.AjfPageBreakModule, typeof i19.AjfTableModule, typeof i20.AjfTextModule, typeof i21.AjfFormsModule, typeof i22.CommonModule, typeof i23.AjfReportsModule, typeof i24.AjfTranslocoModule], [typeof i10.AjfReportRenderer, typeof i2.AjfReportWidget]>;
    static ɵinj: i0.ɵɵInjectorDeclaration<AjfReportsModule>;
}
