/** @externs */
/**
 * @externs
 * @suppress {duplicate,checkTypes}
 */
// NOTE: generated by tsickle, do not edit.
// externs from ERROR: getGeneratedExterns called without rootDir:
/** @const */
var gc_ajf$src$material$form$2dbuilder$condition$2deditor = {};
/** @type {?} */
var monaco;
